// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: brands.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const brandExists = `-- name: BrandExists :one
SELECT EXISTS(SELECT 1 FROM brands WHERE slug = $1)
`

func (q *Queries) BrandExists(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, brandExists, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createBrand = `-- name: CreateBrand :exec
INSERT INTO brands (id, name, slug, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateBrandParams struct {
	ID        string           `json:"id"`
	Name      string           `json:"name"`
	Slug      string           `json:"slug"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) CreateBrand(ctx context.Context, arg CreateBrandParams) error {
	_, err := q.db.Exec(ctx, createBrand,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteBrandByID = `-- name: DeleteBrandByID :exec
DELETE FROM brands
WHERE id = $1
`

func (q *Queries) DeleteBrandByID(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteBrandByID, id)
	return err
}

const getAllBrands = `-- name: GetAllBrands :many
SELECT id, name, slug, created_at, updated_at
FROM brands
ORDER BY created_at DESC
`

func (q *Queries) GetAllBrands(ctx context.Context) ([]Brand, error) {
	rows, err := q.db.Query(ctx, getAllBrands)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Brand
	for rows.Next() {
		var i Brand
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBrandByID = `-- name: GetBrandByID :one
SELECT id, name, slug, created_at, updated_at
FROM brands
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetBrandByID(ctx context.Context, id string) (Brand, error) {
	row := q.db.QueryRow(ctx, getBrandByID, id)
	var i Brand
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBrandBySlug = `-- name: GetBrandBySlug :one
SELECT id, name, slug, created_at, updated_at
FROM brands
WHERE slug = $1
LIMIT 1
`

func (q *Queries) GetBrandBySlug(ctx context.Context, slug string) (Brand, error) {
	row := q.db.QueryRow(ctx, getBrandBySlug, slug)
	var i Brand
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBrandByID = `-- name: UpdateBrandByID :exec
UPDATE brands
SET name = $2, slug = $3, updated_at = NOW()
WHERE id = $1
`

type UpdateBrandByIDParams struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) UpdateBrandByID(ctx context.Context, arg UpdateBrandByIDParams) error {
	_, err := q.db.Exec(ctx, updateBrandByID, arg.ID, arg.Name, arg.Slug)
	return err
}
