// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :exec
INSERT INTO products (id, brand_id, category_id, name, slug, description, is_active, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateProductParams struct {
	ID          string           `json:"id"`
	BrandID     string           `json:"brand_id"`
	CategoryID  string           `json:"category_id"`
	Name        string           `json:"name"`
	Slug        string           `json:"slug"`
	Description string           `json:"description"`
	IsActive    bool             `json:"is_active"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) error {
	_, err := q.db.Exec(ctx, createProduct,
		arg.ID,
		arg.BrandID,
		arg.CategoryID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteProductByID = `-- name: DeleteProductByID :exec
DELETE FROM products
WHERE id = $1
`

func (q *Queries) DeleteProductByID(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteProductByID, id)
	return err
}

const getAllProducts = `-- name: GetAllProducts :many
SELECT id, brand_id, category_id, name, slug, description, is_active, created_at, updated_at
FROM products
ORDER BY created_at DESC
`

func (q *Queries) GetAllProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, getAllProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.BrandID,
			&i.CategoryID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, brand_id, category_id, name, slug, description, is_active, created_at, updated_at
FROM products
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetProductByID(ctx context.Context, id string) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.BrandID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductBySlug = `-- name: GetProductBySlug :one
SELECT id, brand_id, category_id, name, slug, description, is_active, created_at, updated_at
FROM products
WHERE slug = $1
LIMIT 1
`

func (q *Queries) GetProductBySlug(ctx context.Context, slug string) (Product, error) {
	row := q.db.QueryRow(ctx, getProductBySlug, slug)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.BrandID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const productExists = `-- name: ProductExists :one
SELECT EXISTS(SELECT 1 FROM products WHERE slug = $1)
`

func (q *Queries) ProductExists(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, productExists, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateProductByID = `-- name: UpdateProductByID :exec
UPDATE products
SET 
    brand_id = $2,
    category_id = $3,
    name = $4,
    slug = $5,
    description = $6,
    is_active = $7,
    updated_at = NOW()
WHERE id = $1
`

type UpdateProductByIDParams struct {
	ID          string `json:"id"`
	BrandID     string `json:"brand_id"`
	CategoryID  string `json:"category_id"`
	Name        string `json:"name"`
	Slug        string `json:"slug"`
	Description string `json:"description"`
	IsActive    bool   `json:"is_active"`
}

func (q *Queries) UpdateProductByID(ctx context.Context, arg UpdateProductByIDParams) error {
	_, err := q.db.Exec(ctx, updateProductByID,
		arg.ID,
		arg.BrandID,
		arg.CategoryID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.IsActive,
	)
	return err
}
