// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: two_factor_otps.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTwoFactorOTP = `-- name: CreateTwoFactorOTP :exec
INSERT INTO two_factor_otps (id, user_id, challenge_id, code_hash, expires_at, used_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateTwoFactorOTPParams struct {
	ID          string           `json:"id"`
	UserID      string           `json:"user_id"`
	ChallengeID string           `json:"challenge_id"`
	CodeHash    string           `json:"code_hash"`
	ExpiresAt   pgtype.Timestamp `json:"expires_at"`
	UsedAt      pgtype.Timestamp `json:"used_at"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) CreateTwoFactorOTP(ctx context.Context, arg CreateTwoFactorOTPParams) error {
	_, err := q.db.Exec(ctx, createTwoFactorOTP,
		arg.ID,
		arg.UserID,
		arg.ChallengeID,
		arg.CodeHash,
		arg.ExpiresAt,
		arg.UsedAt,
		arg.CreatedAt,
	)
	return err
}

const deleteExpiresTwoFactorOTP = `-- name: DeleteExpiresTwoFactorOTP :exec
DELETE FROM two_factor_otps
WHERE expires_at < NOW() OR used_at IS NOT NULL
`

func (q *Queries) DeleteExpiresTwoFactorOTP(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiresTwoFactorOTP)
	return err
}

const getTwoFactorOTPByChallengeID = `-- name: GetTwoFactorOTPByChallengeID :one
SELECT id, user_id, challenge_id, code_hash, expires_at, used_at, created_at
FROM two_factor_otps
WHERE challenge_id = $1
LIMIT 1
`

func (q *Queries) GetTwoFactorOTPByChallengeID(ctx context.Context, challengeID string) (TwoFactorOtp, error) {
	row := q.db.QueryRow(ctx, getTwoFactorOTPByChallengeID, challengeID)
	var i TwoFactorOtp
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChallengeID,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markTwoFactorOTPUsed = `-- name: MarkTwoFactorOTPUsed :exec
UPDATE two_factor_otps
SET used_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkTwoFactorOTPUsed(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markTwoFactorOTPUsed, id)
	return err
}
