// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_roles.sql

package sqlc

import (
	"context"
)

const assignRoleToUser = `-- name: AssignRoleToUser :exec
INSERT INTO user_roles (user_id, role_id, created_at)
VALUES ($1, $2, NOW())
ON CONFLICT(user_id, role_id) DO NOTHING
`

type AssignRoleToUserParams struct {
	UserID string `json:"user_id"`
	RoleID string `json:"role_id"`
}

func (q *Queries) AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) error {
	_, err := q.db.Exec(ctx, assignRoleToUser, arg.UserID, arg.RoleID)
	return err
}

const getPrimaryRoleByUserID = `-- name: GetPrimaryRoleByUserID :one
SELECT r.name 
FROM user_roles ur
JOIN roles r ON r.id = ur.role_id
WHERE ur.user_id = $1
ORDER BY ur.created_at ASC
LIMIT 1
`

func (q *Queries) GetPrimaryRoleByUserID(ctx context.Context, userID string) (string, error) {
	row := q.db.QueryRow(ctx, getPrimaryRoleByUserID, userID)
	var name string
	err := row.Scan(&name)
	return name, err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT id
FROM roles
WHERE name = $1
LIMIT 1
`

func (q *Queries) GetRoleByName(ctx context.Context, name string) (string, error) {
	row := q.db.QueryRow(ctx, getRoleByName, name)
	var id string
	err := row.Scan(&id)
	return id, err
}
